name: Git hub action workflow
on: push
jobs:
  action-demo: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print
        run: cat index.html



      
